package boot;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "ProductInfo")
public class ProductInfo {
    private String id;
    private String msrp;
    private String cost;
 
    // private String id;
    // private String uid;
    // private String title;
    // private String schema;
    // private String modifiedBy;
    // private Date modifiedDate;

    public ProductInfo() {}
    public ProductInfo(String msrp, String cost) {
        this.msrp = msrp;
        this.cost = cost;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
 
    @DynamoDBAttribute
    public String getMsrp() { return msrp; }
    public void setMsrp(String msrp) { this.msrp = msrp; }
 
    @DynamoDBAttribute
    public String getCost() { return cost; }
    public void setCost(String cost) { this.cost = cost; }
}